<?php

namespace ContainerXqjiefh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Listener_DoctrineSchemaService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'contao.listener.doctrine_schema' shared service.
     *
     * @return \Contao\CoreBundle\EventListener\DoctrineSchemaListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/EventListener/DoctrineSchemaListener.php';

        $a = ($container->privates['contao.doctrine.dca_schema_provider'] ?? $container->load('getContao_Doctrine_DcaSchemaProviderService'));

        if (isset($container->privates['contao.listener.doctrine_schema'])) {
            return $container->privates['contao.listener.doctrine_schema'];
        }

        return $container->privates['contao.listener.doctrine_schema'] = new \Contao\CoreBundle\EventListener\DoctrineSchemaListener($a);
    }
}
