<?php

namespace ContainerXqjiefh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Image_PictureGeneratorService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'contao.image.picture_generator' shared service.
     *
     * @return \Contao\Image\PictureGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/contao/image/src/PictureGeneratorInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/contao/image/src/PictureGenerator.php';
        include_once \dirname(__DIR__, 3).'/vendor/contao/image/src/ResizeCalculator.php';

        $a = ($container->services['contao.image.legacy_resizer'] ?? $container->load('getContao_Image_LegacyResizerService'));

        if (isset($container->services['contao.image.picture_generator'])) {
            return $container->services['contao.image.picture_generator'];
        }

        return $container->services['contao.image.picture_generator'] = new \Contao\Image\PictureGenerator($a, ($container->privates['contao.image.resize_calculator'] ?? ($container->privates['contao.image.resize_calculator'] = new \Contao\Image\ResizeCalculator())));
    }
}
