<?php

namespace ContainerXqjiefh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Command_AutomatorService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'contao.command.automator' shared service.
     *
     * @return \Contao\CoreBundle\Command\AutomatorCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Command/AutomatorCommand.php';

        $container->privates['contao.command.automator'] = $instance = new \Contao\CoreBundle\Command\AutomatorCommand(($container->services['contao.framework'] ?? $container->getContao_FrameworkService()));

        $instance->setName('contao:automator');
        $instance->setDescription('Runs automator tasks on the command line.');

        return $instance;
    }
}
