<?php

namespace ContainerXqjiefh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Doctrine_Backup_RetentionPolicyService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'contao.doctrine.backup.retention_policy' shared service.
     *
     * @return \Contao\CoreBundle\Doctrine\Backup\RetentionPolicy
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Doctrine/Backup/RetentionPolicyInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Doctrine/Backup/RetentionPolicy.php';

        return $container->privates['contao.doctrine.backup.retention_policy'] = new \Contao\CoreBundle\Doctrine\Backup\RetentionPolicy(5, [0 => '1D', 1 => '7D', 2 => '14D', 3 => '1M']);
    }
}
