<?php

namespace ContainerXqjiefh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFragment_HandlerService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'fragment.handler' shared service.
     *
     * @return \Contao\CoreBundle\Fragment\FragmentHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/http-kernel/Fragment/FragmentHandler.php';
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Fragment/FragmentHandler.php';

        $a = ($container->privates['contao.fragment.handler.inner'] ?? $container->load('getContao_Fragment_Handler_InnerService'));

        if (isset($container->services['fragment.handler'])) {
            return $container->services['fragment.handler'];
        }

        return $container->services['fragment.handler'] = new \Contao\CoreBundle\Fragment\FragmentHandler(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'esi' => ['privates', 'fragment.renderer.esi', 'getFragment_Renderer_EsiService', true],
            'forward' => ['privates', 'contao.fragment.forward_renderer', 'getContao_Fragment_ForwardRendererService', true],
            'hinclude' => ['privates', 'fragment.renderer.hinclude', 'getFragment_Renderer_HincludeService', true],
            'inline' => ['privates', 'fragment.renderer.inline', 'getFragment_Renderer_InlineService', true],
        ], [
            'esi' => 'Symfony\\Component\\HttpKernel\\Fragment\\EsiFragmentRenderer',
            'forward' => 'Contao\\CoreBundle\\Fragment\\ForwardFragmentRenderer',
            'hinclude' => 'Symfony\\Component\\HttpKernel\\Fragment\\HIncludeFragmentRenderer',
            'inline' => 'Symfony\\Component\\HttpKernel\\Fragment\\InlineFragmentRenderer',
        ]), $a, ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['contao.fragment.registry'] ?? $container->getContao_Fragment_RegistryService()), ($container->privates['contao.fragment.pre_handlers'] ?? ($container->privates['contao.fragment.pre_handlers'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [], []))), true);
    }
}
