<?php

namespace ContainerXqjiefh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Context_ContaoBackendService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'security.firewall.map.context.contao_backend' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-bundle/Security/FirewallContext.php';

        $a = ($container->privates['security.exception_listener.contao_backend'] ?? $container->load('getSecurity_ExceptionListener_ContaoBackendService'));

        if (isset($container->privates['security.firewall.map.context.contao_backend'])) {
            return $container->privates['security.firewall.map.context.contao_backend'];
        }
        $b = ($container->privates['security.logout_listener.contao_backend'] ?? $container->load('getSecurity_LogoutListener_ContaoBackendService'));

        if (isset($container->privates['security.firewall.map.context.contao_backend'])) {
            return $container->privates['security.firewall.map.context.contao_backend'];
        }

        return $container->privates['security.firewall.map.context.contao_backend'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallContext(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['security.channel_listener'] ?? $container->load('getSecurity_ChannelListenerService'));
            yield 1 => ($container->privates['security.context_listener.0'] ?? $container->load('getSecurity_ContextListener_0Service'));
            yield 2 => ($container->privates['contao.security.login_authentication_listener.contao_backend'] ?? $container->load('getContao_Security_LoginAuthenticationListener_ContaoBackendService'));
            yield 3 => ($container->privates['security.authentication.listener.anonymous.contao_backend'] ?? $container->load('getSecurity_Authentication_Listener_Anonymous_ContaoBackendService'));
            yield 4 => ($container->privates['security.authentication.switchuser_listener.contao_backend'] ?? $container->load('getSecurity_Authentication_SwitchuserListener_ContaoBackendService'));
            yield 5 => ($container->privates['security.access_listener'] ?? $container->load('getSecurity_AccessListenerService'));
        }, 6), $a, $b, ($container->privates['security.firewall.map.config.contao_backend'] ?? $container->load('getSecurity_Firewall_Map_Config_ContaoBackendService')));
    }
}
