<?php

namespace ContainerXqjiefh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Context_ContaoFrontendService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'security.firewall.map.context.contao_frontend' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-bundle/Security/FirewallContext.php';

        $a = ($container->privates['security.logout_listener.contao_frontend'] ?? $container->load('getSecurity_LogoutListener_ContaoFrontendService'));

        if (isset($container->privates['security.firewall.map.context.contao_frontend'])) {
            return $container->privates['security.firewall.map.context.contao_frontend'];
        }

        return $container->privates['security.firewall.map.context.contao_frontend'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallContext(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['security.channel_listener'] ?? $container->load('getSecurity_ChannelListenerService'));
            yield 1 => ($container->privates['security.context_listener.1'] ?? $container->load('getSecurity_ContextListener_1Service'));
            yield 2 => ($container->privates['contao.security.login_authentication_listener.contao_frontend'] ?? $container->load('getContao_Security_LoginAuthenticationListener_ContaoFrontendService'));
            yield 3 => ($container->privates['security.authentication.listener.rememberme.contao_frontend'] ?? $container->load('getSecurity_Authentication_Listener_Rememberme_ContaoFrontendService'));
            yield 4 => ($container->privates['security.authentication.listener.anonymous.contao_frontend'] ?? $container->load('getSecurity_Authentication_Listener_Anonymous_ContaoFrontendService'));
            yield 5 => ($container->privates['security.access_listener'] ?? $container->load('getSecurity_AccessListenerService'));
        }, 6), ($container->privates['security.exception_listener.contao_frontend'] ?? $container->load('getSecurity_ExceptionListener_ContaoFrontendService')), $a, ($container->privates['security.firewall.map.config.contao_frontend'] ?? $container->load('getSecurity_Firewall_Map_Config_ContaoFrontendService')));
    }
}
