<?php

namespace ContainerOlOcZDD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Doctrine_Backup_DumperService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'contao.doctrine.backup.dumper' shared service.
     *
     * @return \Contao\CoreBundle\Doctrine\Backup\Dumper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Doctrine/Backup/DumperInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Doctrine/Backup/Dumper.php';

        return $container->privates['contao.doctrine.backup.dumper'] = new \Contao\CoreBundle\Doctrine\Backup\Dumper();
    }
}
