<?php

namespace ContainerOlOcZDD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Doctrine_SchemaProviderService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'contao.doctrine.schema_provider' shared service.
     *
     * @return \Contao\CoreBundle\Doctrine\Schema\SchemaProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Doctrine/Schema/SchemaProvider.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        if (isset($container->privates['contao.doctrine.schema_provider'])) {
            return $container->privates['contao.doctrine.schema_provider'];
        }

        return $container->privates['contao.doctrine.schema_provider'] = new \Contao\CoreBundle\Doctrine\Schema\SchemaProvider($a);
    }
}
