<?php

namespace ContainerOlOcZDD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Picker_BuilderService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'contao.picker.builder' shared service.
     *
     * @return \Contao\CoreBundle\Picker\PickerBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Picker/PickerBuilderInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Picker/PickerBuilder.php';

        $container->services['contao.picker.builder'] = $instance = new \Contao\CoreBundle\Picker\PickerBuilder(($container->services['knp_menu.factory'] ?? $container->load('getKnpMenu_FactoryService')), ($container->services['router'] ?? $container->getRouterService()));

        $instance->addProvider(($container->privates['contao.picker.page_provider'] ?? $container->load('getContao_Picker_PageProviderService')));
        $instance->addProvider(($container->privates['contao.picker.file_provider'] ?? $container->load('getContao_Picker_FileProviderService')));
        $instance->addProvider(($container->privates['contao.picker.article_provider'] ?? $container->load('getContao_Picker_ArticleProviderService')));
        $instance->addProvider(($container->privates['contao.picker.table_provider'] ?? $container->load('getContao_Picker_TableProviderService')));

        return $instance;
    }
}
