<?php

namespace ContainerOlOcZDD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Menu_MatcherService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'contao.menu.matcher' shared service.
     *
     * @return \Knp\Menu\Matcher\Matcher
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['contao.menu.matcher'] = new \Knp\Menu\Matcher\Matcher();
    }
}
