<?php

namespace ContainerOlOcZDD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Cache_EntityTagsService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'contao.cache.entity_tags' shared service.
     *
     * @return \Contao\CoreBundle\Cache\EntityCacheTags
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Cache/EntityCacheTags.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        if (isset($container->services['contao.cache.entity_tags'])) {
            return $container->services['contao.cache.entity_tags'];
        }

        return $container->services['contao.cache.entity_tags'] = new \Contao\CoreBundle\Cache\EntityCacheTags($a, NULL, NULL);
    }
}
