<?php

namespace ContainerOlOcZDD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInsertTagsControllerService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'Contao\CoreBundle\Controller\InsertTagsController' shared service.
     *
     * @return \Contao\CoreBundle\Controller\InsertTagsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Controller/InsertTagsController.php';

        return $container->services['Contao\\CoreBundle\\Controller\\InsertTagsController'] = new \Contao\CoreBundle\Controller\InsertTagsController(($container->services['contao.insert_tag.parser'] ?? $container->load('getContao_InsertTag_ParserService')));
    }
}
