<?php

namespace ContainerOlOcZDD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersisterInterfaceService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'Scheb\TwoFactorBundle\Model\PersisterInterface' shared service.
     *
     * @return \Scheb\TwoFactorBundle\Model\Persister\DoctrinePersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/scheb/2fa-bundle/Model/PersisterInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/scheb/2fa-bundle/Model/Persister/DoctrinePersister.php';

        return $container->services['Scheb\\TwoFactorBundle\\Model\\PersisterInterface'] = ($container->privates['scheb_two_factor.persister_factory.doctrine'] ?? $container->load('getSchebTwoFactor_PersisterFactory_DoctrineService'))->getPersister();
    }
}
