<?php

namespace ContainerPLnfdKK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RvEsqSzService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.RvEsqSz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RvEsqSz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'model' => ['privates', '.errored..service_locator.RvEsqSz.Contao\\ModuleModel', NULL, 'Cannot autowire service ".service_locator.RvEsqSz": it references class "Contao\\ModuleModel" but no such service exists.'],
            'template' => ['privates', '.errored..service_locator.RvEsqSz.Contao\\Template', NULL, 'Cannot autowire service ".service_locator.RvEsqSz": it references class "Contao\\Template" but no such service exists.'],
        ], [
            'model' => 'Contao\\ModuleModel',
            'template' => 'Contao\\Template',
        ]);
    }
}
