<?php

namespace ContainerPLnfdKK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Filesystem_MountManagerService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'contao.filesystem.mount_manager' shared service.
     *
     * @return \Contao\CoreBundle\Filesystem\MountManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Filesystem/MountManager.php';

        $container->privates['contao.filesystem.mount_manager'] = $instance = new \Contao\CoreBundle\Filesystem\MountManager(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['contao.filesystem.public_uri.symlinked_local_files_provider'] ?? $container->load('getContao_Filesystem_PublicUri_SymlinkedLocalFilesProviderService'));
        }, 1));

        $instance->mount(($container->privates['contao.filesystem.adapter.files'] ?? $container->load('getContao_Filesystem_Adapter_FilesService')), 'files');
        $instance->mount(($container->privates['contao.filesystem.adapter.backups'] ?? $container->load('getContao_Filesystem_Adapter_BackupsService')), 'backups');

        return $instance;
    }
}
