<?php

namespace ContainerPLnfdKK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpMenu_FactoryExtension_RoutingService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'knp_menu.factory_extension.routing' shared service.
     *
     * @return \Knp\Menu\Integration\Symfony\RoutingExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/knplabs/knp-menu/src/Knp/Menu/Factory/ExtensionInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/knplabs/knp-menu/src/Knp/Menu/Integration/Symfony/RoutingExtension.php';

        $a = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->privates['knp_menu.factory_extension.routing'])) {
            return $container->privates['knp_menu.factory_extension.routing'];
        }

        return $container->privates['knp_menu.factory_extension.routing'] = new \Knp\Menu\Integration\Symfony\RoutingExtension($a);
    }
}
