<?php

namespace ContainerJfZHTtD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Routing_ResponseContextAccessorService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'contao.routing.response_context_accessor' shared service.
     *
     * @return \Contao\CoreBundle\Routing\ResponseContext\ResponseContextAccessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Routing/ResponseContext/ResponseContextAccessor.php';

        return $container->services['contao.routing.response_context_accessor'] = new \Contao\CoreBundle\Routing\ResponseContext\ResponseContextAccessor(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
