<?php

namespace ContainerJfZHTtD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Security_ExpiringTokenBasedRememberMeServices_ContaoFrontendService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'contao.security.expiring_token_based_remember_me_services.contao_frontend' shared service.
     *
     * @return \Contao\CoreBundle\Security\Authentication\RememberMe\ExpiringTokenBasedRememberMeServices
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-http/RememberMe/RememberMeServicesInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-http/Logout/LogoutHandlerInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/symfony/security-http/RememberMe/AbstractRememberMeServices.php';
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Security/Authentication/RememberMe/ExpiringTokenBasedRememberMeServices.php';

        return $container->privates['contao.security.expiring_token_based_remember_me_services.contao_frontend'] = new \Contao\CoreBundle\Security\Authentication\RememberMe\ExpiringTokenBasedRememberMeServices(($container->privates['contao.repository.remember_me'] ?? $container->load('getContao_Repository_RememberMeService')), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['contao.security.frontend_user_provider'] ?? $container->load('getContao_Security_FrontendUserProviderService'));
        }, 1), $container->getEnv('APP_SECRET'), 'contao_frontend', ['remember_me_parameter' => 'autologin', 'name' => 'REMEMBERME', 'lifetime' => 31536000, 'path' => '/', 'domain' => NULL, 'secure' => false, 'httponly' => true, 'samesite' => NULL, 'always_remember_me' => false], ($container->privates['monolog.logger.security'] ?? $container->load('getMonolog_Logger_SecurityService')));
    }
}
