<?php

namespace ContainerJfZHTtD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Image_PreviewFactoryService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'contao.image.preview_factory' shared service.
     *
     * @return \Contao\CoreBundle\Image\Preview\PreviewFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Image/Preview/PreviewFactory.php';

        return $container->services['contao.image.preview_factory'] = new \Contao\CoreBundle\Image\Preview\PreviewFactory(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['contao.image.imagine_preview_provider'] ?? $container->load('getContao_Image_ImaginePreviewProviderService'));
            yield 1 => ($container->privates['contao.image.fallback_preview_provider'] ?? ($container->privates['contao.image.fallback_preview_provider'] = new \Contao\CoreBundle\Image\Preview\FallbackPreviewProvider()));
        }, 2), ($container->services['contao.image.factory'] ?? $container->load('getContao_Image_FactoryService')), ($container->services['contao.image.picture_factory'] ?? $container->load('getContao_Image_PictureFactoryService')), ($container->services['contao.image.studio'] ?? $container->load('getContao_Image_StudioService')), ($container->services['contao.framework'] ?? $container->getContao_FrameworkService()), $container->getEnv('APP_SECRET'), (\dirname(__DIR__, 3).'/assets/previews'), $container->parameters['contao.image.valid_extensions'], 512, 1024);
    }
}
