<?php

namespace ContainerJfZHTtD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Twig_PictureConfigurationRuntimeService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'contao.twig.picture_configuration_runtime' shared service.
     *
     * @return \Contao\CoreBundle\Twig\Runtime\PictureConfigurationRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Twig/Runtime/PictureConfigurationRuntime.php';

        return $container->privates['contao.twig.picture_configuration_runtime'] = new \Contao\CoreBundle\Twig\Runtime\PictureConfigurationRuntime();
    }
}
