<?php

namespace ContainerJfZHTtD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Fragment_Contao_FrontendModule_RootPageDependentModulesService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'contao.fragment._contao.frontend_module.root_page_dependent_modules' shared service.
     *
     * @return \Contao\CoreBundle\Controller\FrontendModule\RootPageDependentModulesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php';
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Controller/FrontendModule/RootPageDependentModulesController.php';

        $container->services['contao.fragment._contao.frontend_module.root_page_dependent_modules'] = $instance = new \Contao\CoreBundle\Controller\FrontendModule\RootPageDependentModulesController();

        $a = $container->load('get_ServiceLocator__A7R9no_Contao_Fragment_Contao_FrontendModule_RootPageDependentModulesService');

        $instance->setContainer($a);
        $instance->setFragmentOptions(['category' => 'miscellaneous', 'type' => 'root_page_dependent_modules', 'debugController' => 'Contao\\CoreBundle\\Controller\\FrontendModule\\RootPageDependentModulesController', 'template' => 'mod_root_page_dependent_modules']);
        $instance->setContainer($a);

        return $instance;
    }
}
