<?php

namespace ContainerJfZHTtD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Cron_LegacyService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'contao.cron.legacy' shared service.
     *
     * @return \Contao\CoreBundle\Cron\LegacyCron
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/contao/core-bundle/src/Cron/LegacyCron.php';

        $a = ($container->services['contao.framework'] ?? $container->getContao_FrameworkService());

        if (isset($container->privates['contao.cron.legacy'])) {
            return $container->privates['contao.cron.legacy'];
        }

        return $container->privates['contao.cron.legacy'] = new \Contao\CoreBundle\Cron\LegacyCron($a);
    }
}
