<?php

namespace ContainerJfZHTtD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpMenu_FactoryService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'knp_menu.factory' shared service.
     *
     * @return \Knp\Menu\MenuFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/knplabs/knp-menu/src/Knp/Menu/FactoryInterface.php';
        include_once \dirname(__DIR__, 3).'/vendor/knplabs/knp-menu/src/Knp/Menu/MenuFactory.php';

        $container->services['knp_menu.factory'] = $instance = new \Knp\Menu\MenuFactory();

        $instance->addExtension(($container->privates['knp_menu.factory_extension.routing'] ?? $container->load('getKnpMenu_FactoryExtension_RoutingService')), 0);

        return $instance;
    }
}
