services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    nahati\ContaoIsotopeStockBundle\EventListener\:
        resource: '../../../src/EventListener/'
        

