<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXqjiefh\Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXqjiefh/Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXqjiefh.legacy');

    return;
}

if (!\class_exists(Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXqjiefh\Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer::class, Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer::class, false);
}

return new \ContainerXqjiefh\Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer([
    'container.build_hash' => 'Xqjiefh',
    'container.build_id' => 'e447f1d2',
    'container.build_time' => 1691450470,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXqjiefh');
