<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJfZHTtD\Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJfZHTtD/Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJfZHTtD.legacy');

    return;
}

if (!\class_exists(Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJfZHTtD\Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer::class, Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer::class, false);
}

return new \ContainerJfZHTtD\Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer([
    'container.build_hash' => 'JfZHTtD',
    'container.build_id' => '6f1239a5',
    'container.build_time' => 1691515271,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJfZHTtD');
