<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'contao_backend' => [[], ['_scope' => 'backend', '_token_check' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\BackendController::mainAction'], [], [['text', '/contao']], [], [], []],
    'contao_backend_login' => [[], ['_scope' => 'backend', '_token_check' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\BackendController::loginAction'], [], [['text', '/contao/login']], [], [], []],
    'contao_backend_logout' => [[], ['_scope' => 'backend', '_token_check' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\BackendController::logoutAction'], [], [['text', '/contao/logout']], [], [], []],
    'contao_backend_password' => [[], ['_scope' => 'backend', '_token_check' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\BackendController::passwordAction'], [], [['text', '/contao/password']], [], [], []],
    'contao_backend_confirm' => [[], ['_scope' => 'backend', '_token_check' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\BackendController::confirmAction'], [], [['text', '/contao/confirm']], [], [], []],
    'contao_backend_file' => [[], ['_scope' => 'backend', '_token_check' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\BackendController::fileAction'], [], [['text', '/contao/file']], [], [], []],
    'contao_backend_help' => [[], ['_scope' => 'backend', '_token_check' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\BackendController::helpAction'], [], [['text', '/contao/help']], [], [], []],
    'contao_backend_page' => [[], ['_scope' => 'backend', '_token_check' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\BackendController::pageAction'], [], [['text', '/contao/page']], [], [], []],
    'contao_backend_popup' => [[], ['_scope' => 'backend', '_token_check' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\BackendController::popupAction'], [], [['text', '/contao/popup']], [], [], []],
    'contao_backend_alerts' => [[], ['_scope' => 'backend', '_token_check' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\BackendController::alertsAction'], [], [['text', '/contao/alerts']], [], [], []],
    'contao_backend_picker' => [[], ['_scope' => 'backend', '_token_check' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\BackendController::pickerAction'], [], [['text', '/contao/picker']], [], [], []],
    'contao_backend_preview' => [[], ['_scope' => 'backend', '_allow_preview' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\BackendPreviewController'], [], [['text', '/contao/preview']], [], [], []],
    'contao_backend_switch' => [[], ['_scope' => 'backend', '_allow_preview' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\BackendPreviewSwitchController'], [], [['text', '/contao/preview_switch']], [], [], []],
    'contao_frontend_captcha' => [['_locale'], ['_scope' => 'frontend', '_controller' => 'Contao\\CoreBundle\\Controller\\CaptchaController'], [], [['variable', '/', '[^/]++', '_locale', true], ['text', '/_contao/captcha']], [], [], []],
    'contao_core_favicon__invoke' => [[], ['_scope' => 'frontend', '_controller' => 'Contao\\CoreBundle\\Controller\\FaviconController'], [], [['text', '/favicon.ico']], [], [], []],
    'contao_frontend_cron' => [[], ['_scope' => 'frontend', '_token_check' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\FrontendController::cronAction'], [], [['text', '/_contao/cron']], [], [], []],
    'contao_frontend_share' => [[], ['_scope' => 'frontend', '_token_check' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\FrontendController::shareAction'], [], [['text', '/_contao/share']], [], [], []],
    'contao_frontend_logout' => [[], ['_scope' => 'frontend', '_token_check' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\FrontendController::logoutAction'], [], [['text', '/_contao/logout']], [], [], []],
    'contao_frontend_check_cookies' => [[], ['_scope' => 'frontend', '_token_check' => false, '_controller' => 'Contao\\CoreBundle\\Controller\\FrontendController::checkCookiesAction'], [], [['text', '/_contao/check_cookies']], [], [], []],
    'contao_frontend_request_token_script' => [[], ['_scope' => 'frontend', '_token_check' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\FrontendController::requestTokenScriptAction'], [], [['text', '/_contao/request_token_script']], [], [], []],
    'contao_initialize' => [[], ['_controller' => 'Contao\\CoreBundle\\Controller\\InitializeController'], [], [['text', '/_contao/initialize']], [], [], []],
    'contao_preview_link' => [['id'], ['_scope' => 'frontend', '_allow_preview' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\PreviewLinkController'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/_contao/preview']], [], [], []],
    'contao_core_robotstxt__invoke' => [[], ['_scope' => 'frontend', '_controller' => 'Contao\\CoreBundle\\Controller\\RobotsTxtController'], [], [['text', '/robots.txt']], [], [], []],
    'contao_core_sitemap__invoke' => [[], ['_scope' => 'frontend', '_controller' => 'Contao\\CoreBundle\\Controller\\SitemapController'], [], [['text', '/sitemap.xml']], [], [], []],
    'contao_images' => [['path'], ['_controller' => 'Contao\\CoreBundle\\Controller\\ImagesController', '_bypass_maintenance' => true], ['path' => '.+'], [['variable', '/', '.+', 'path', true], ['text', '/assets/images']], [], [], []],
    'contao_backend_redirect' => [[], ['_scope' => 'backend', '_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction', 'route' => 'contao_backend', 'permanent' => true], [], [['text', '/contao/']], [], [], []],
];
