<?php

namespace ContainerFxx6L5u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5ijE3KRService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.5ijE3KR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5ijE3KR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pageModel' => ['privates', '.errored..service_locator.5ijE3KR.Contao\\PageModel', NULL, 'Cannot autowire service ".service_locator.5ijE3KR": it references class "Contao\\PageModel" but no such service exists.'],
        ], [
            'pageModel' => 'Contao\\PageModel',
        ]);
    }
}
