<?php

namespace ContainerFxx6L5u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Picker_TableProviderService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'contao.picker.table_provider' shared service.
     *
     * @return \Contao\CoreBundle\Picker\TablePickerProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Picker/PickerProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Picker/DcaPickerProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Picker/PickerMenuInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Picker/AbstractTablePickerProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Picker/TablePickerProvider.php';

        return $container->privates['contao.picker.table_provider'] = new \Contao\CoreBundle\Picker\TablePickerProvider(($container->services['contao.framework'] ?? $container->getContao_FrameworkService()), ($container->services['knp_menu.factory'] ?? $container->load('getKnpMenu_FactoryService')), ($container->services['router'] ?? $container->getRouterService()), ($container->services['translator'] ?? $container->getTranslatorService()), ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()));
    }
}
