<?php

namespace ContainerFxx6L5u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Listener_ExceptionConverterService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'contao.listener.exception_converter' shared service.
     *
     * @return \Contao\CoreBundle\EventListener\ExceptionConverterListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php';

        return $container->privates['contao.listener.exception_converter'] = new \Contao\CoreBundle\EventListener\ExceptionConverterListener();
    }
}
