<?php

namespace ContainerFxx6L5u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Image_SizesService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the public 'contao.image.sizes' shared service.
     *
     * @return \Contao\CoreBundle\Image\ImageSizes
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Image/ImageSizes.php';

        return $container->services['contao.image.sizes'] = new \Contao\CoreBundle\Image\ImageSizes(($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->services['contao.framework'] ?? $container->getContao_FrameworkService()), ($container->services['translator'] ?? $container->getTranslatorService()));
    }
}
