<?php

namespace ContainerFxx6L5u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authentication_Rememberme_Services_Simplehash_ContaoFrontend_TwoFactorDecoratorService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'security.authentication.rememberme.services.simplehash.contao_frontend.two_factor_decorator' shared service.
     *
     * @return \Scheb\TwoFactorBundle\Security\Authentication\RememberMe\RememberMeServicesDecorator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/RememberMe/RememberMeServicesInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Logout/LogoutHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/scheb/2fa-bundle/Security/Authentication/RememberMe/RememberMeServicesDecorator.php';

        $a = ($container->privates['contao.security.expiring_token_based_remember_me_services.contao_frontend'] ?? $container->load('getContao_Security_ExpiringTokenBasedRememberMeServices_ContaoFrontendService'));

        if (isset($container->privates['security.authentication.rememberme.services.simplehash.contao_frontend.two_factor_decorator'])) {
            return $container->privates['security.authentication.rememberme.services.simplehash.contao_frontend.two_factor_decorator'];
        }

        return $container->privates['security.authentication.rememberme.services.simplehash.contao_frontend.two_factor_decorator'] = new \Scheb\TwoFactorBundle\Security\Authentication\RememberMe\RememberMeServicesDecorator($a);
    }
}
