<?php

namespace ContainerFxx6L5u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchebTwoFactor_DefaultBackupCodeManagerService extends Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer
{
    /**
     * Gets the private 'scheb_two_factor.default_backup_code_manager' shared service.
     *
     * @return \Scheb\TwoFactorBundle\Security\TwoFactor\Backup\BackupCodeManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/scheb/2fa-backup-code/Security/TwoFactor/Backup/BackupCodeManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/scheb/2fa-backup-code/Security/TwoFactor/Backup/BackupCodeManager.php';

        return $container->privates['scheb_two_factor.default_backup_code_manager'] = new \Scheb\TwoFactorBundle\Security\TwoFactor\Backup\BackupCodeManager(($container->services['Scheb\\TwoFactorBundle\\Model\\PersisterInterface'] ?? $container->load('getPersisterInterfaceService')));
    }
}
