services:
  _defaults:
    autowire: true
    autoconfigure: true
    
  nahati\ContaoIsotopeStockBundle\EventListener\:
    resource: "../src/EventListener/"

  nahati\ContaoIsotopeStockBundle\Helper\:
    resource: "../src/Helper/"
