<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK4ZPpWE\Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK4ZPpWE/Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerK4ZPpWE.legacy');

    return;
}

if (!\class_exists(Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerK4ZPpWE\Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer::class, Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer::class, false);
}

return new \ContainerK4ZPpWE\Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer([
    'container.build_hash' => 'K4ZPpWE',
    'container.build_id' => '521b171c',
    'container.build_time' => 1689184519,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK4ZPpWE');
