<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxx6L5u\Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxx6L5u/Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFxx6L5u.legacy');

    return;
}

if (!\class_exists(Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFxx6L5u\Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer::class, Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer::class, false);
}

return new \ContainerFxx6L5u\Nahati_ContaoIsotopeStockBundle_Tests_Integration_app_AppKernelTestDebugContainer([
    'container.build_hash' => 'Fxx6L5u',
    'container.build_id' => '5d9e86c9',
    'container.build_time' => 1688401295,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFxx6L5u');
