name: Deploy to GitHub Pages

on:
    push:
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            issues: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy unit test reports to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs/unit
                  publish_branch: gh-pages

            - name: Deploy integration test reports to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs/integration
                  publish_branch: gh-pages
