name: CI

on:
    pull_request: ~
    push: ~

jobs:
    ecs:
        name: ECS
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1 # Run with the lowest supported to avoid incompatible fixes
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none
              env:
                  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: |
                  composer install --no-interaction --no-progress
                  composer bin ecs install --no-interaction --no-progress
            - name: Run ECS
              run: tools/ecs/vendor/bin/ecs check src tests --config ecs.php --no-progress-bar --ansi --fix

    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none
              env:
                  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: |
                  composer install --no-interaction --no-progress
                  composer bin phpstan install --no-interaction --no-progress
            - name: Run PHPStan
              run: tools/phpstan/vendor/bin/phpstan analyse --no-progress

    tests:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.1]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: xdebug
              env:
                  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Initialize the database
              run: |
                  sudo /etc/init.d/mysql start
                  mysql -uroot -proot -e "CREATE database ContaoIsotopeStockBundleTest"

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer install --no-interaction --no-progress

            - name: Run PHPUnit with code coverage
              run: vendor/bin/phpunit --colors=always --testsuite=unit --coverage-html docs/unit --testdox-html docs/unit/testdox.html
              env:
                  DATABASE_URL: mysql://root:root@127.0.0.1:3306/ContaoIsotopeStockBundleTest

            - name: Upload Unit Test Coverage Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: unit-coverage
                  path: docs/unit

            - name: Upload TestDox Report Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: unit-testdox-report
                  path: docs/unit/testdox.html

            - name: Run the functional tests with PDO MySQL
              run: vendor/bin/phpunit  --testsuite=integration --colors=always --coverage-html docs/integration --testdox-html docs/integration/testdox.html
              env:
                  DATABASE_URL: mysql://root:root@127.0.0.1:3306/ContaoIsotopeStockBundleTest

            - name: Upload Integration Test Coverage Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: integration-coverage
                  path: docs/integration

            - name: Upload TestDox Report Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: integration-testdox-report
                  path: docs/integration/testdox.html
