name: CI

on:
    pull_request:
    push:

jobs:
    tests:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.1, 8.2, 8.3]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom,fileinfo,filter,gd,hash,intl,json,mbstring,mysqli,pcre,pdo_mysql,zlib
                  coverage: xdebug
              env:
                  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Initialize the database
              run: |
                  sudo /etc/init.d/mysql start
                  mysql -uroot -proot -e "CREATE database ContaoIsotopeStockBundleTest"

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer install --no-interaction --no-progress

            - name: Create directories for test reports
              run: mkdir -p docs/unit docs/integration

            - name: Run PHPUnit with code coverage
              run: vendor/bin/phpunit --colors=always --testsuite=unit --coverage-html docs/unit --testdox-text docs/unit/testdox.txt
              env:
                  DATABASE_URL: mysql://root:root@127.0.0.1:3306/ContaoIsotopeStockBundleTest

            - name: Upload test reports as artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: test-reports
                  path: |
                      docs/unit
